// <auto-generated />
using System;
using System.Collections.Generic;
using Maliev.PaymentService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.PaymentService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    partial class PaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.PaymentService.Core.Entities.PaymentProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Dictionary<string, string>>("Credentials")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("credentials");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("SupportedCurrencies")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supported_currencies");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_payment_providers_deleted_at");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_providers_name");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_payment_providers_priority");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_payment_providers_status");

                    b.ToTable("payment_providers", (string)null);
                });

            modelBuilder.Entity("Maliev.PaymentService.Core.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CancelUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cancel_url");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("order_id");

                    b.Property<Guid>("PaymentProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_provider_id");

                    b.Property<string>("PaymentUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("payment_url");

                    b.Property<string>("ProviderErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_error_code");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_name");

                    b.Property<string>("ProviderTransactionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_transaction_id");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("ReturnUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("return_url");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("'\\x00'::bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_payment_transactions_correlation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_payment_transactions_created_at");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_payment_transactions_customer_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_transactions_idempotency_key");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_payment_transactions_order_id");

                    b.HasIndex("PaymentProviderId")
                        .HasDatabaseName("ix_payment_transactions_payment_provider_id");

                    b.HasIndex("ProviderTransactionId")
                        .HasDatabaseName("ix_payment_transactions_provider_transaction_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_payment_transactions_status");

                    b.ToTable("payment_transactions", (string)null);
                });

            modelBuilder.Entity("Maliev.PaymentService.Core.Entities.ProviderConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("api_base_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxRetries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("max_retries");

                    b.Property<Guid>("PaymentProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_provider_id");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region");

                    b.Property<int>("TimeoutSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("timeout_seconds");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_provider_configurations_is_active");

                    b.HasIndex("PaymentProviderId")
                        .HasDatabaseName("ix_provider_configurations_payment_provider_id");

                    b.HasIndex("PaymentProviderId", "Region")
                        .IsUnique()
                        .HasDatabaseName("ix_provider_configurations_provider_region");

                    b.ToTable("provider_configurations", (string)null);
                });

            modelBuilder.Entity("Maliev.PaymentService.Core.Entities.RefundTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTime?>("InitiatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initiated_at");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("internal_notes");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<Guid>("PaymentTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_transaction_id");

                    b.Property<string>("ProviderErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_error_code");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<string>("ProviderRefundId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_refund_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("RefundType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("refund_type");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("'\\x00'::bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("idx_refund_transactions_correlation_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uk_refund_transactions_idempotency_key");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("idx_refund_transactions_provider_id");

                    b.HasIndex("PaymentTransactionId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_refund_transactions_payment_id");

                    b.HasIndex("Status", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_refund_transactions_status");

                    b.ToTable("refund_transactions", null, t =>
                        {
                            t.HasCheckConstraint("chk_refund_transactions_amount_positive", "amount > 0");

                            t.HasCheckConstraint("chk_refund_transactions_currency_length", "LENGTH(currency) = 3");

                            t.HasCheckConstraint("chk_refund_transactions_status", "status IN ('pending', 'processing', 'completed', 'failed')");

                            t.HasCheckConstraint("chk_refund_transactions_type", "refund_type IN ('full', 'partial')");
                        });
                });

            modelBuilder.Entity("Maliev.PaymentService.Core.Entities.TransactionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_details");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("new_status");

                    b.Property<Guid>("PaymentTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_transaction_id");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("previous_status");

                    b.Property<string>("ProviderResponse")
                        .HasColumnType("jsonb")
                        .HasColumnName("provider_response");

                    b.Property<Guid?>("RefundTransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_transaction_logs_correlation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_transaction_logs_created_at");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_transaction_logs_event_type");

                    b.HasIndex("PaymentTransactionId")
                        .HasDatabaseName("ix_transaction_logs_payment_transaction_id");

                    b.HasIndex("RefundTransactionId");

                    b.ToTable("transaction_logs", (string)null);
                });

            modelBuilder.Entity("Maliev.PaymentService.Core.Entities.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("next_retry_at");

                    b.Property<Dictionary<string, object>>("ParsedPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_payload");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_transaction_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<int>("ProcessingAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processing_attempts");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("processing_status");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_event_id");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_payload");

                    b.Property<Guid?>("RefundTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("refund_transaction_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("'\\x00'::bytea");

                    b.Property<string>("Signature")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("signature");

                    b.Property<bool>("SignatureValidated")
                        .HasColumnType("boolean")
                        .HasColumnName("signature_validated");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_webhook_events");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_webhook_events_created_at");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("idx_webhook_events_next_retry")
                        .HasFilter("next_retry_at IS NOT NULL");

                    b.HasIndex("PaymentTransactionId")
                        .HasDatabaseName("idx_webhook_events_payment_id")
                        .HasFilter("payment_transaction_id IS NOT NULL");

                    b.HasIndex("RefundTransactionId")
                        .HasDatabaseName("idx_webhook_events_refund_id")
                        .HasFilter("refund_transaction_id IS NOT NULL");

                    b.HasIndex("ProcessingStatus", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_webhook_events_processing_status");

                    b.HasIndex("ProviderId", "ProviderEventId")
                        .IsUnique()
                        .HasDatabaseName("uk_webhook_events_provider_event");

                    b.ToTable("webhook_events", null, t =>
                        {
                            t.HasCheckConstraint("chk_webhook_events_attempts", "processing_attempts >= 0");

                            t.HasCheckConstraint("chk_webhook_events_processing_status", "processing_status IN ('Pending', 'Processing', 'Completed', 'Failed', 'Duplicate')");
                        });
                });

            modelBuilder.Entity("Maliev.PaymentService.Core.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("Maliev.PaymentService.Core.Entities.PaymentProvider", "PaymentProvider")
                        .WithMany()
                        .HasForeignKey("PaymentProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentProvider");
                });

            modelBuilder.Entity("Maliev.PaymentService.Core.Entities.ProviderConfiguration", b =>
                {
                    b.HasOne("Maliev.PaymentService.Core.Entities.PaymentProvider", "PaymentProvider")
                        .WithMany("Configurations")
                        .HasForeignKey("PaymentProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentProvider");
                });

            modelBuilder.Entity("Maliev.PaymentService.Core.Entities.RefundTransaction", b =>
                {
                    b.HasOne("Maliev.PaymentService.Core.Entities.PaymentTransaction", "PaymentTransaction")
                        .WithMany()
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refund_transactions_payment_transactions");

                    b.HasOne("Maliev.PaymentService.Core.Entities.PaymentProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refund_transactions_payment_providers");

                    b.Navigation("PaymentTransaction");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Maliev.PaymentService.Core.Entities.TransactionLog", b =>
                {
                    b.HasOne("Maliev.PaymentService.Core.Entities.PaymentTransaction", "PaymentTransaction")
                        .WithMany("TransactionLogs")
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maliev.PaymentService.Core.Entities.RefundTransaction", null)
                        .WithMany("TransactionLogs")
                        .HasForeignKey("RefundTransactionId");

                    b.Navigation("PaymentTransaction");
                });

            modelBuilder.Entity("Maliev.PaymentService.Core.Entities.WebhookEvent", b =>
                {
                    b.HasOne("Maliev.PaymentService.Core.Entities.PaymentTransaction", "PaymentTransaction")
                        .WithMany()
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_webhook_events_payment_transactions");

                    b.HasOne("Maliev.PaymentService.Core.Entities.PaymentProvider", "PaymentProvider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_webhook_events_payment_providers");

                    b.Navigation("PaymentProvider");

                    b.Navigation("PaymentTransaction");
                });

            modelBuilder.Entity("Maliev.PaymentService.Core.Entities.PaymentProvider", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("Maliev.PaymentService.Core.Entities.PaymentTransaction", b =>
                {
                    b.Navigation("TransactionLogs");
                });

            modelBuilder.Entity("Maliev.PaymentService.Core.Entities.RefundTransaction", b =>
                {
                    b.Navigation("TransactionLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
