name: Build and Test

env:
  ServiceDefaultsVersion: 1.0.81-alpha
  MessagingContractsVersion: 1.0.91-alpha

on:
  workflow_call:
    inputs:
      solution_file:
        required: true
        type: string
      configuration:
        required: false
        type: string
        default: Release
    secrets:
      gitops_pat:
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Service
        uses: actions/checkout@v5
        with:
          path: service

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.x"

      - name: Restore dependencies
        run: dotnet restore ${{ inputs.solution_file }}
        working-directory: service
        env:
          NUGET_USERNAME: ${{ github.actor }}
          NUGET_PASSWORD: ${{ secrets.gitops_pat }}

      - name: Build
        run: dotnet build ${{ inputs.solution_file }} --no-restore --configuration ${{ inputs.configuration }}
        working-directory: service

      - name: Test
        run: dotnet test ${{ inputs.solution_file }} --no-build --configuration ${{ inputs.configuration }} --verbosity normal
        working-directory: service
