name: PR Validation

env:
  ServiceDefaultsVersion: 1.0.81-alpha
  MessagingContractsVersion: 1.0.91-alpha

on:
  pull_request:
    branches: [develop, staging, main]

jobs:
  build-and-test:
    uses: ./.github/workflows/_build-and-test.yml
    with:
      solution_file: Maliev.PaymentService.slnx
    secrets:
      gitops_pat: ${{ secrets.GITOPS_PAT }}
